(require 'paredit)

(define-key paredit-mode-map (kbd "s-<left>") nil)
(define-key paredit-mode-map (kbd "M-<down>") nil)
(define-key paredit-mode-map (kbd "M-<up>") nil)
(define-key paredit-mode-map (kbd "s-<right>") nil)
(define-key paredit-mode-map (kbd "s-S-<left>") nil)
(define-key paredit-mode-map (kbd "s-S-<right>") nil)
(define-key paredit-mode-map (kbd "M-q") nil)
(define-key paredit-mode-map (kbd "M-s") nil)
(define-key paredit-mode-map (kbd "M-d") nil)
(define-key paredit-mode-map (kbd "M-;") nil)
(define-key paredit-mode-map (kbd "s-r") 'paredit-raise-sexp)
(define-key paredit-mode-map (kbd "s-s") 'paredit-splice-sexp)
(define-key paredit-mode-map (kbd "<return>") 'paredit-newline)
(define-key paredit-mode-map (kbd "S-<return>") (kbd "C-e <return> <tab>"))

(define-key paredit-mode-map (kbd "s-e") 'cider-eval-last-sexp)

(provide 'myparedit)
